### ISSUE TITLE
does not work with code blocks

### ISSUE THREAD

**Issue by laoshaw** [Scuilion/markdown-drawer#6]
my headings are `#, ##, ###` etc, if I have a code block (e.g. bash) that contains some comment lines with #, this plugin will treat those code as headings.

**Comment by Scuilion** [comment]
@laoshaw I am unable to reproduce this issue. Could you please provide a full markdown file that triggers the issue?

**Comment by laoshaw** [comment]
here it goes:

```
## This is a test

first issue, quote does not escape so  `#` will be treated as header.

second issue, the end of this line is again treated as header # as comments

```bash
# this should not be a header but it is by markdowndrawer - third issue
echo "testing"

## again this should not a header either - fourth issue

echo "testing"
```

### more headers

In short, everything has the pound sign will be treated as headers.
```

**Comment by Scuilion** [comment]
Okay, I understand better. 

The first two issue are definitely bugs.

Could not recreate the last issue. Please confirm that you have the latest code [244a78](https://github.com/Scuilion/markdown-drawer/commit/244a78234c0faadbcc8d062ebf9de0eefa6fcd72). I change from manually determining fenced code to using vim built-in function `synstack`.

I had a bit of trouble with the example so I recreated it as a [gist](https://gist.github.com/Scuilion/41b1386e1af67c454dbcecf9ca18f25b).

**Comment by laoshaw** [comment]
yes I use #244a78 indeed

**Comment by laoshaw** [comment]
just tested with the gist and it still shows pound sign as head titles. git sha1 is 47b45778

**Comment by Scuilion** [comment]
Could you let me now the type/version/os of vi that you are using?

**Comment by laoshaw** [comment]
ubuntu 18.04, vim 8.2 from its PPA

**Comment by Scuilion** [comment]
This is what I get every time. (╯°□°)╯︵ ┻━┻
![GIFrecord_2020-05-31_193956](https://user-images.githubusercontent.com/241151/83366745-9fc24980-a376-11ea-979b-17d5c6451b1d.gif)

**Comment by Scuilion** [comment]
@laoshaw there appears to be a problem if vim does not recognize the file as markdown. What is the extension of the file you are trying to view?

When you get the error run `:set filetype?` and see what type of file vim is recognizing it as. 

I've created issue #7 to prevent the drawer from rendering if the file is not recognize as markdown.
