### ISSUE TITLE
Only run if filetype is Markdown

### ISSUE THREAD

**Issue by Scuilion** [Scuilion/markdown-drawer#7]
Check fro file type `:set filetype?` to be `markdown` otherwise drawer will fail on fenced code.

**Comment by armandfavrot** [comment]
So I tried to use it with an Rmd file and it didn't work. But it worked perfectly with a md file. Is there a chance to have it working with Rmd files soon ?

**Comment by Scuilion** [comment]
The plugin only loads when it recognizes a markdown type file. Add the following to you ~/.vimrc and .Rmd files will be recognized:
```
au BufRead,BufNewFile *.Rmd set filetype=markdown
```
